### ISSUE TITLE
Matches info: 0 inliers, 0 confidence

### ISSUE THREAD

**Issue by SHL2023** [akashrai2003/ImageStitchingCPP-BoschProject#1]
Hello, I'm experiencing an issue while using your repository. I'm running the finalVersion.cpp use my own images, and here is the Error message:
Finding features...
Features in image #1: 500
Features in image #2: 500
Finding features, time: 1.20525 sec
Pairwise matching
Matches info: 0 inliers, 0 confidence
Matches info: 0 inliers, 0 confidence
Matches info: 0 inliers, 0 confidence
Matches info: 0 inliers, 0 confidence
Pairwise matching, time: 0.016546 sec
Saving matches graph...
Need more images
![catch](https://github.com/akashrai2003/ImageStitchingCPP-BoschProject/assets/127490834/7f725f4d-650c-452e-98d3-08c2d696cf12)
it seems can't find any Matches. But when i run the Project3.exe, using same images, and the output is fine. Could you kindly assist me with this problem?

**Comment by akashrai2003** [comment]
Hey, thanks for going through the repo, actually we have been using a default features i.e. ORB features in our .exe file as here the whole code is uploaded but in the documentation it was mentioned that as of now we've been focusing on ORB features and haven't tried to optimise other features for matching the points, so there might be some issues related to other features.

But still if the exe file is able to stitch the images this code should be working fine as well. I would like to ask another question that are you using the Command line based executable from GUI dir here or the StaticLinkedExecutable. As the executable in GUI has been further optimised to select the best features automatically and then stitch the images. The code will be pushed in some time.

**Comment by akashrai2003** [comment]
Also another thing that I can help you out is with trying other matching feature like surf,sift and akaze. For doing that you can go into the [research/ImageStichingExampleDetailed.cpp](https://github.com/akashrai2003/ImageStitchingCPP-BoschProject/blob/main/research/ImageStichingExampleDetailed.cpp) and just make a few changes in the code in your main file by adding a few lines from line 369 of finalVersion.cpp


```
    LOGLN("Finding features...");
#if ENABLE_LOG
    int64 t = getTickCount();
#endif

    Ptr<Feature2D> finder;
    if (features_type == "orb")
    {
        finder = ORB::create();
    }
    else if (features_type == "akaze")
    {
        finder = AKAZE::create();
    }
#ifdef HAVE_OPENCV_XFEATURES2D
    else if (features_type == "surf")
    {
        finder = xfeatures2d::SURF::create();
    }
#endif
    else if (features_type == "sift")
    {
        finder = SIFT::create();
    }
    else
    {
        cout << "Unknown 2D features type: '" << features_type << "'.\n";
        return -1;
    }
```


Also you can try changing the default values under the headers or while executing the program from the Command Line you can use `.\Project3.exe img3.jpg img1.jpg img4.jpg img2.jpg --features orb --matcher homography     --save_graph match.dot` where you can change the features value to surf sift etc. and try it out.

**Comment by SHL2023** [comment]
I think I figured it out. From line 89 of finalVersion.cpp:
```
#ifdef HAVE_OPENCV_XFEATURES2D
string features_type = "orb";
float match_conf = 0.65f;
#else
string features_type = "orb";
float match_conf = 0.3f;
#endif
```
leave only
```
string features_type = "orb";
float match_conf = 0.3f;
```
and delete the rest. Now it's working, thank you for your reply.

**Comment by akashrai2003** [comment]
I'll be closing the issue now.
